"""Local fixture data for demos and early development."""

from __future__ import annotations

from app.db.models import Platform, StatusCheck, StatusMessage, StatusResult, WorkItem

DEFAULT_PLATFORMS = (
    Platform(
        id="platform-001",
        name="Databricks",
        owner="Platform Ops",
        state="operational",
        created_at="2024-06-01T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:42:00Z",
        updated_by="seed",
    ),
    Platform(
        id="platform-002",
        name="Power BI",
        owner="BI Enablement",
        state="monitoring",
        created_at="2024-05-20T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:30:00Z",
        updated_by="seed",
    ),
    Platform(
        id="platform-003",
        name="Service Portal",
        owner="Platform Ops",
        state="operational",
        created_at="2024-07-01T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:32:00Z",
        updated_by="seed",
    ),
    Platform(
        id="platform-004",
        name="Fabric Gateway",
        owner="Data Engineering",
        state="monitoring",
        created_at="2024-06-15T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:25:00Z",
        updated_by="seed",
    ),
    Platform(
        id="platform-005",
        name="Data Lake Storage",
        owner="Data Platform",
        state="monitoring",
        created_at="2024-06-10T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T07:55:00Z",
        updated_by="seed",
    ),
)

DEFAULT_STATUS_CHECKS = (
    StatusCheck(
        id="status-001",
        platform_id="platform-001",
        name="SQL Warehouse Refresh",
        check_type="freshness",
        owner_group="Platform Ops",
        description="Monitor SQL warehouse refresh freshness.",
        sla_minutes=15,
        warn_after_minutes=20,
        crit_after_minutes=30,
        state="enabled",
        version=1,
        created_at="2024-06-15T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:42:00Z",
        updated_by="seed",
    ),
    StatusCheck(
        id="status-004",
        platform_id="platform-001",
        name="Unity Catalog Sync",
        check_type="freshness",
        owner_group="Platform Ops",
        description="Track Unity Catalog metadata sync timing.",
        sla_minutes=20,
        warn_after_minutes=30,
        crit_after_minutes=60,
        state="enabled",
        version=1,
        created_at="2024-06-20T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:30:00Z",
        updated_by="seed",
    ),
    StatusCheck(
        id="status-002",
        platform_id="platform-002",
        name="Dataset Sync",
        check_type="freshness",
        owner_group="BI Enablement",
        description="Monitor Power BI dataset refresh cadence.",
        sla_minutes=30,
        warn_after_minutes=45,
        crit_after_minutes=90,
        state="enabled",
        version=1,
        created_at="2024-05-25T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:10:00Z",
        updated_by="seed",
    ),
    StatusCheck(
        id="status-005",
        platform_id="platform-002",
        name="Gateway Heartbeat",
        check_type="availability",
        owner_group="BI Enablement",
        description="Heartbeat check for Power BI gateway.",
        sla_minutes=10,
        warn_after_minutes=15,
        crit_after_minutes=30,
        state="enabled",
        version=1,
        created_at="2024-05-25T08:05:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:05:00Z",
        updated_by="seed",
    ),
    StatusCheck(
        id="status-003",
        platform_id="platform-003",
        name="Portal API",
        check_type="availability",
        owner_group="Platform Ops",
        description="API availability and latency check.",
        sla_minutes=10,
        warn_after_minutes=15,
        crit_after_minutes=25,
        state="enabled",
        version=1,
        created_at="2024-07-01T08:00:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:30:00Z",
        updated_by="seed",
    ),
    StatusCheck(
        id="status-006",
        platform_id="platform-003",
        name="Frontend Build",
        check_type="freshness",
        owner_group="Platform Ops",
        description="Front-end build pipeline freshness.",
        sla_minutes=30,
        warn_after_minutes=45,
        crit_after_minutes=90,
        state="enabled",
        version=1,
        created_at="2024-07-01T08:05:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:32:00Z",
        updated_by="seed",
    ),
    StatusCheck(
        id="status-007",
        platform_id="platform-004",
        name="Fabric Capacity",
        check_type="availability",
        owner_group="Data Engineering",
        description="Fabric capacity utilization signal.",
        sla_minutes=20,
        warn_after_minutes=30,
        crit_after_minutes=60,
        state="enabled",
        version=1,
        created_at="2024-06-20T08:10:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:25:00Z",
        updated_by="seed",
    ),
    StatusCheck(
        id="status-008",
        platform_id="platform-004",
        name="Spark Pools",
        check_type="availability",
        owner_group="Data Engineering",
        description="Spark pool autoscaling check.",
        sla_minutes=30,
        warn_after_minutes=45,
        crit_after_minutes=75,
        state="enabled",
        version=1,
        created_at="2024-06-20T08:15:00Z",
        created_by="seed",
        updated_at="2024-07-18T08:12:00Z",
        updated_by="seed",
    ),
)

DEFAULT_STATUS_RESULTS = (
    StatusResult(
        id="result-001",
        check_id="status-001",
        platform_id="platform-001",
        state="green",
        measured_at="2024-07-18T08:40:00Z",
        created_at="2024-07-18T08:41:00Z",
        observed_value="freshness=6m",
        message="All clusters responding",
        ingestion_run_id="run-004",
    ),
    StatusResult(
        id="result-009",
        check_id="status-001",
        platform_id="platform-001",
        state="green",
        measured_at="2024-07-18T09:10:00Z",
        created_at="2024-07-18T09:11:00Z",
        observed_value="freshness=4m",
        message="Warehouse stable",
        ingestion_run_id="run-005",
    ),
    StatusResult(
        id="result-002",
        check_id="status-004",
        platform_id="platform-001",
        state="yellow",
        measured_at="2024-07-18T07:45:00Z",
        created_at="2024-07-18T07:46:00Z",
        observed_value="freshness=48m",
        message="Sync backlog growing",
        ingestion_run_id="run-004",
    ),
    StatusResult(
        id="result-003",
        check_id="status-002",
        platform_id="platform-002",
        state="yellow",
        measured_at="2024-07-18T08:10:00Z",
        created_at="2024-07-18T08:11:00Z",
        observed_value="freshness=18m",
        message="Refresh queue delayed",
        ingestion_run_id="run-004",
    ),
    StatusResult(
        id="result-004",
        check_id="status-005",
        platform_id="platform-002",
        state="red",
        measured_at="2024-07-18T08:05:00Z",
        created_at="2024-07-18T08:06:00Z",
        observed_value="heartbeat=down",
        message="Gateway unreachable from tenant",
        ingestion_run_id="run-004",
    ),
    StatusResult(
        id="result-005",
        check_id="status-003",
        platform_id="platform-003",
        state="green",
        measured_at="2024-07-18T08:30:00Z",
        created_at="2024-07-18T08:31:00Z",
        observed_value="freshness=3m",
        message="Latency within SLA",
        ingestion_run_id="run-004",
    ),
    StatusResult(
        id="result-006",
        check_id="status-006",
        platform_id="platform-003",
        state="green",
        measured_at="2024-07-18T08:32:00Z",
        created_at="2024-07-18T08:33:00Z",
        observed_value="pipeline=green",
        message="Build pipeline green",
        ingestion_run_id="run-004",
    ),
    StatusResult(
        id="result-007",
        check_id="status-007",
        platform_id="platform-004",
        state="yellow",
        measured_at="2024-07-18T08:25:00Z",
        created_at="2024-07-18T08:26:00Z",
        observed_value="utilization=92%",
        message="Capacity near limit",
        ingestion_run_id="run-004",
    ),
    StatusResult(
        id="result-008",
        check_id="status-008",
        platform_id="platform-004",
        state="green",
        measured_at="2024-07-18T08:12:00Z",
        created_at="2024-07-18T08:13:00Z",
        observed_value="nodes=stable",
        message="Autoscaling steady",
        ingestion_run_id="run-004",
    ),
)

DEFAULT_STATUS_MESSAGES = (
    StatusMessage(
        id="message-006",
        platform_id=None,
        severity="warning",
        title="Service review in progress",
        body_md="Engineering is reviewing degraded signals on the platform.",
        state="published",
        created_at="2024-07-18T08:20:00Z",
        start_at="2024-07-18T08:15:00Z",
        end_at=None,
    ),
    StatusMessage(
        id="message-003",
        platform_id="platform-001",
        severity="critical",
        title="Warehouse incident",
        body_md="Investigating intermittent SQL Warehouse errors.",
        state="published",
        created_at="2024-07-18T08:05:00Z",
        start_at="2024-07-18T07:50:00Z",
        end_at=None,
    ),
    StatusMessage(
        id="message-004",
        platform_id="platform-004",
        severity="info",
        title="Capacity scaling",
        body_md="Autoscaling is adding capacity to stay within limits.",
        state="published",
        created_at="2024-07-18T07:55:00Z",
        start_at="2024-07-18T07:30:00Z",
        end_at=None,
    ),
    StatusMessage(
        id="message-005",
        platform_id="platform-003",
        severity="info",
        title="Release checklist",
        body_md="Preparing a routine deployment with no expected impact.",
        state="draft",
        created_at="2024-07-18T07:40:00Z",
        start_at=None,
        end_at=None,
    ),
    StatusMessage(
        id="message-002",
        platform_id="platform-002",
        severity="warning",
        title="Power BI refresh delays",
        body_md="Dataset refresh queues are running late.",
        state="published",
        created_at="2024-07-18T07:20:00Z",
        start_at="2024-07-18T07:00:00Z",
        end_at=None,
    ),
    StatusMessage(
        id="message-001",
        platform_id=None,
        severity="info",
        title="Scheduled maintenance",
        body_md="Routine maintenance window tonight.",
        state="published",
        created_at="2024-07-18T06:00:00Z",
        start_at="2024-07-18T22:00:00Z",
        end_at="2024-07-19T00:00:00Z",
    ),
)

DEFAULT_WORK_ITEMS = (
    WorkItem(
        id="work-001",
        platform_id="platform-001",
        title="Access request: finance workspace",
        state="open",
        priority="medium",
        created_at="2024-07-18T08:30:00Z",
        requester="alex@example.com",
    ),
    WorkItem(
        id="work-002",
        platform_id="platform-002",
        title="Incident: refresh lag",
        state="triage",
        priority="high",
        created_at="2024-07-18T07:55:00Z",
        requester="bi-ops@example.com",
    ),
    WorkItem(
        id="work-003",
        platform_id=None,
        title="Doc update: onboarding checklist",
        state="open",
        priority="low",
        created_at="2024-07-18T07:40:00Z",
        requester="docs@example.com",
    ),
)
